name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: |
        sudo apt-get update
        sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
        cargo build --verbose
        cargo test --verbose
